package com.oyms.model;

import java.util.Date;

import org.springframework.stereotype.Component;

@Component
public class GoodType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodtype.id
     *
     * @mbg.generated Mon Oct 28 16:48:09 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodtype.good_type
     *
     * @mbg.generated Mon Oct 28 16:48:09 CST 2019
     */
    private String goodType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodtype.sub_type
     *
     * @mbg.generated Mon Oct 28 16:48:09 CST 2019
     */
    private String subType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodtype.isdelete
     *
     * @mbg.generated Mon Oct 28 16:48:09 CST 2019
     */
    private Byte isdelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goodtype.create_time
     *
     * @mbg.generated Mon Oct 28 16:48:09 CST 2019
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodtype.id
     *
     * @return the value of goodtype.id
     *
     * @mbg.generated Mon Oct 28 16:48:09 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodtype.id
     *
     * @param id the value for goodtype.id
     *
     * @mbg.generated Mon Oct 28 16:48:09 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodtype.good_type
     *
     * @return the value of goodtype.good_type
     *
     * @mbg.generated Mon Oct 28 16:48:09 CST 2019
     */
    public String getGoodType() {
        return goodType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodtype.good_type
     *
     * @param goodType the value for goodtype.good_type
     *
     * @mbg.generated Mon Oct 28 16:48:09 CST 2019
     */
    public void setGoodType(String goodType) {
        this.goodType = goodType == null ? null : goodType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodtype.sub_type
     *
     * @return the value of goodtype.sub_type
     *
     * @mbg.generated Mon Oct 28 16:48:09 CST 2019
     */
    public String getSubType() {
        return subType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodtype.sub_type
     *
     * @param subType the value for goodtype.sub_type
     *
     * @mbg.generated Mon Oct 28 16:48:09 CST 2019
     */
    public void setSubType(String subType) {
        this.subType = subType == null ? null : subType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodtype.isdelete
     *
     * @return the value of goodtype.isdelete
     *
     * @mbg.generated Mon Oct 28 16:48:09 CST 2019
     */
    public Byte getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodtype.isdelete
     *
     * @param isdelete the value for goodtype.isdelete
     *
     * @mbg.generated Mon Oct 28 16:48:09 CST 2019
     */
    public void setIsdelete(Byte isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goodtype.create_time
     *
     * @return the value of goodtype.create_time
     *
     * @mbg.generated Mon Oct 28 16:48:09 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goodtype.create_time
     *
     * @param createTime the value for goodtype.create_time
     *
     * @mbg.generated Mon Oct 28 16:48:09 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}